weather/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('weatherapp.urls')),
]

weatherapp/urls.py
from django.urls import path,include
from weatherapp import views

app_name = 'weatherapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('export/',views.export,name='export'),
]

weatherapp/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class City(models.Model):
    # TODO: Define fields here
    name = models.CharField(max_length=100,primary_key=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural='cities'

class CityWeather(models.Model):
    # TODO: Define fields here
    city = models.CharField(max_length=100)
    temperature = models.FloatField(max_length=10)
    pressure = models.FloatField(max_length=10)
    windspeed = models.FloatField(max_length=10)
    humidity = models.FloatField(max_length=10)
    description = models.CharField(max_length=50)
    icon = models.SlugField(null=True)
    date = models.DateTimeField(default=datetime.now()) 
    def __str__(self):
        return self.city

weatherapp/forms.py
from django import forms
from .models import City

class CityForm(forms.ModelForm):
    name = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'class':'form-control mr-sm-2','placeholder':'Search'}))
    class Meta:
        model = City
        fields = ['name']

weatherapp/views.py
from django.shortcuts import render
import requests
from .forms import CityForm
from django.http import HttpResponse
from .models import City,CityWeather
import csv
# Create your views here.
def index(request):
    city='mumbai'
    cities= City.objects.all()
    #login in openweathermap for API id in url
    url = 'https://api.openweathermap.org/data/2.5/weather?q={}&appid={}'
    if request.method == 'POST':
        #print(request.POST.dict()['name'])
        form = CityForm(request.POST)
        if form.is_valid():
            form.save()

    form = CityForm()


    weather_list=[]

    for city in cities:

        r= requests.get(url.format(city)).json()
        #print(r)
        city_weather = {
            'city':r['name'],
            'temperature':round(r['main']['temp']-273.15,2),
            'description':r['weather'][0]['description'],
            'icon':r['weather'][0]['icon'],
            'humidity':r['main']['humidity'],
            'pressure':r['main']['pressure'],
            'windspeed':r['wind']['speed']
        }
        new_values = CityWeather(**city_weather)
        new_values.save()
        weather_list.append(city_weather)
    context_dict  = {'weather_list':weather_list,'form':form}
    return  render(request, 'weatherapp/weather.html',context=context_dict)


def export(request):
    response = HttpResponse()
    writer = csv.writer(response)
    writer.writerow(['date','city','temperature','description','humidity','pressure','windspeed'])
    for city in CityWeather.objects.all().values_list('date','city','temperature','description','humidity','pressure','windspeed'):
        writer.writerow(city)

    response['Content-Disposition']='attachment;filename="weatherhistory.csv"'
    return response

weatherapp/templates/weatherapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title>WeatherX</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	</head>
	<body style="background-color:#DDF8E8">
		<nav class="navbar navbar-dark bg-dark">
			<div class="container">
				<a class="navbar-brand" href="#">
					<img src="https://cdn2.iconfinder.com/data/icons/weather-flat-14/64/weather02-512.png" width="70" height="70" class="d-inline-block align-top" alt="" loading="lazy">
					<a class="navbar-brand mr-auto" href="#"><h1>WeatherX</h1> </a>
				</a>
			</div>
		</nav>
		<div class="container">
			<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#251F47">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'weatherapp:index' %}">Home<span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
						</li>
						<li class="nav-item my-sm-0">
							<a class="nav-link" href="{% url 'weatherapp:export' %}">Download weather data</a>
						</li>
						
					</ul>
				</div>
			</nav>
		</div>
		
		<div class="container">
			<div class="jumbotron" style="background-color:#404E7C">
				<form class="form-inline my-2 my-lg-0" method="POST" >
					{% csrf_token %}
					{{form}}
					<input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Add your city">
				</form>
			</div>
		</div>
		{% block body %}
		{% endblock body %}
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	</body>
</html>

weatherapp/templates/weatherapp/weather.html
{% extends "weatherapp/base.html" %}
{% block body %}
<!--##################################################################################
################################ CARDS  ################################################
################################################################################### -->
		<div class="container">
			<div class="row">
				{% for city_weather in weather_list %}
					<div class="col-auto">
						<div class="card border-secondary mb-3" style="width: 18rem; background-color:#71B48D;">
							<div class="card-header">
								<nav class="navbar navbar-light" style="background-color:#71B48D;border-radius:10px;">
									<p class="navbar-brand" >
										<img src="https://api.openweathermap.org/img/w/{{city_weather.icon}}.png" width="50" height="50" class="d-inline-block align-top" alt="" loading="lazy">
										<p class="navbar-brand mr-auto" >{{city_weather.city}}</p>
									</p>
								</nav>
							</div>
							<div class="card-body text-secondary" style="background-color:#86CB92">
								<h5 class="card-title">{{city_weather.temperature}}°C</h5>
								<p class="card-text">{{city_weather.description}}</p>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
{% endblock body %}